### PR TITLE
Selection sort

### PR DESCRIPTION
**Pull request by ffmiyo**
Hello Bill,

I'm not quite sure how to best structure the code. 
So i just took the path of least restructure which is following sorting/bubble style.
Let me know if anything needs changing.

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
Can we get back to finishing the tree work firsrt please? I would like for the tree to having functions that reorder the tree instead of just traversing and printing out values. Is that possible?

**Comment by ffmiyo** [comment]
Yea sure, i did intend to finish it up with lookup and insert. I don't quite get what do you mean with reorder. I'm guessing you meant
keeping it balanced?

**Comment by ardan-bkennedy** [comment]
No, but I will take care of it. My print function prints the tree in the order of each layer. I will find a way to take your code and restructure the tree. I am on vacation right now.

**Comment by ffmiyo** [comment]
Restructure how? My guess you want to convert the tree into a balanced tree. I hope i get it right this time xD

**Comment by ardan-bkennedy** [comment]
Sorry, I have been on vacation. I need to re-think this I guess. Maybe we can start with code that deletes nodes from a tree?  I had it in my head that the physical tree would be reordered for some operations like balancing, etc.

Now that I am back from vacation, I will review the traversal code more closely.

**Comment by ardan-bkennedy** [comment]
@ffmiyo can you send me an email please.   bill@ardanlabs.com

**Comment by ffmiyo** [comment]
The existing tree is a binary search tree. The requirements have outgrown its capability. Naturally it should evolve into something like b-tree or avl-tree to gain nicer properties like self-balancing and tree shape not depending on insertion order. 
For current implementation, deletion can be done(tree can still become degenerate) but nothing more.

Sorry, for the extremely late reply, I was on intermittent internet access. 
Should I email you still?

**Comment by ardan-bkennedy** [comment]
Maybe we should get on a video call so we can define what we need/want for this material.  Can you email me at bill@ardanlabs.com

**Pull request closed without merging**
