### PR TITLE
Fix Dockerfile CMD

### PR DESCRIPTION
**Pull request by qjcg**
Change the Dockerfile CMD from `/bin/bash` to `/bin/sh`, since the bash shell isn't installed in the docker base image we're using (`golang:1.9.1-alpine3.6`).

Before this change, running a container based on the `ardanlabs/gotraining` image would fail with a `/bin/bash: not found` error by default.

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
Let's talk about this. Also bringing in @webRat because I don't know enough. We did this for profiling reasons.

**Comment by webRat** [comment]
I pulled this today and ran the instructions straight from the readme.
screen shot 2017-11-16 at 8 29 38 am

I think the `CMD` line needs to be dropped, it does nothing and that line alone isn't enough to keep the container up and running.

**Comment by primos63** [comment]
If I may, you should follow the Docker reference material for [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#shell-form-entrypoint-example) and [CMD](https://docs.docker.com/engine/reference/builder/#cmd).

- Dockerfile should specify at least one of CMD or ENTRYPOINT commands.
- ENTRYPOINT should be defined when using the container as an executable.
- CMD should be used as a way of defining default arguments for an ENTRYPOINT command or for executing an ad-hoc command in a container.

Since the point of the container is to provide a shell where Go is available, you should have and ENTRYPOINT defined:

`ENTRYPOINT [ "/bin/sh" ]`

To run the main.go file in the gotraining directory, one would execute:
`docker run -it --rm -p 8080:8080 -v "$PWD":/go/src/github.com/ardanlabs/gotraining ardanlabs/gotraining:latest go run main.go`

If the purpose of the container is to run that application, then the ENTRYPOINT would be
`ENTRYPOINT [ "go", "run", "main.go" ]`

**Comment by qjcg** [comment]
Agree with @primos63 .

In terms of what to use as the `ENTRYPOINT`, I'd lean toward `[ "/bin/sh" ]`, as it is my understanding that providing a shell with Go installed is the primary purpose of the container, and only sometimes (rarely) do we ask students to run the web application via `go run main.go`.

**Comment by robbyoconnor** [comment]
Everything on this thread is correct.

**Comment by ardan-bkennedy** [comment]
Thanks Everyone!

**Pull request merged**
