### PR TITLE
add a BDD style test example

### PR DESCRIPTION
**Pull request by hoangdangninh**

### CODE REVIEW

**Comment by hoangdangninh** [comment]
it looks like third-party package is not supported in this repo. Is there a way I can get it installed through Travis?

**Comment by ardan-bkennedy** [comment]
I need to talk with the team about this. Give us a day or two. Thank you for taking the time to add this PR.

**Comment by hoangdangninh** [comment]
np, as i went through the repo testing pkg, thought it could be helpful.
Ennovar/gPanel/#37

**Comment by hoangdangninh** [comment]
np, as i went through the testing pkg in your repo, thought this PR could be helpful...
Ennovar/gPanel/#37

**Comment by jcbwlkr** [comment]
Hi, @hoangdangninh! Thanks for making this contribution.

I talked with @ardan-bkennedy and we decided we do not want to include examples for any of the third party testing frameworks. They definitely have value and if they help people then all the more power to them. However for our class we want to focus primarily on how to test with the standard library.

Thanks again and good luck on gPanel!

**Comment by hoangdangninh** [comment]
No prob!

**Pull request closed without merging**
