### PR TITLE
Add mocking to topics/go/testing

### PR DESCRIPTION
**Pull request by ClavinJune**
- Add HTTP call mocking topics

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
I don't believe this is necessary when it comes to HTTP. The httptest package has everything you need to mock calls. You don't need an interface for this.

**Comment by ClavinJune** [comment]
I think httptest needs us to create a mock server, and when it comes to a http call inside a function, it can't mock the request.

Let's say there's a function that needs to call an external URL, how can we test that function without really calls the external URL with httptest?

**Comment by ardan-bkennedy** [comment]
In this case what’s important is not testing the call, you know that will work. What’s important is what happens once you get the data. I would write a function that takes the raw data in and returns the data out. Test that. 

I think this is the biggest mistake people make. If you want to test the call, use the test server. Most of the time what’s more important is the data transformation. 

When you are adding interfaces for the sole purpose of testing, I would argue that’s a smell. Obviously there are exceptions to every rule. Make sure you are taking the exception for the right reason.

**Comment by ClavinJune** [comment]
I see, then, should I close this PR?

**Comment by ardan-bkennedy** [comment]
At this point I don’t think for this starter-kit it’s the right engineering decision. Unless you want to continue to talk about it, yes.

**Pull request closed without merging**
