### PR TITLE
docs(README): fix nav anchor

### PR DESCRIPTION
**Pull request by sashamelentyev**

### CODE REVIEW

**Comment by progzc** [comment]
谢谢，您的来信已经收到！祝身体健康，天天开心                                                              ——赵超

**Comment by ardan-bkennedy** [comment]
Can you please add yourself to the CONTRIBUTORS file.

**Comment by sashamelentyev** [comment]
@ardan-bkennedy done

**Comment by ardan-bkennedy** [comment]
Thanks for this!

**Pull request merged**
