### PR TITLE
Searches Algorithm

### PR DESCRIPTION
**Pull request by Miraddo**
I added some simple searching algorithms with test

- Binary Search
- Linear Search
- Double Linear Search
- Jump Search
- Interpolation Search

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
make sure this code runs through gofmt and staticcheck 

I might just accept the code and make the style changes. Then you can see what I did.

**Comment by Miraddo** [comment]
Thanks, Bill, for reviewing. I did that.

**Comment by Miraddo** [comment]
> make sure this code runs through gofmt and staticcheck
> 
> I might just accept the code and make the style changes. Then you can see what I did.

Thanks, Bill, for reviewing. I did that.

**Comment by ardan-bkennedy** [comment]
I haven't forgotten about this. I will work towards reviewing this next week.

**Comment by Miraddo** [comment]
> I haven't forgotten about this. I will work towards reviewing this next week.

Bill, I appreciate it. I know you are busy as well. Just I want to say It's Ok. If you had free time, it would be great, and also I would be really appreciated it for reviewing my code.

**Comment by ardan-bkennedy** [comment]
Look at the change I made to `binarySearchIterative`. I would like you to make these changes `binarySearchRecursive`. Then from there we can refactor the others.

- Comments must be complete sentences with proper sentence structure and grammar.
- Don't add those tabs/spaces after the //
- Only add comments that are needed to explan things not obvious
- Parameters are local variables and need to start with a lowercase letter
- Look at how the naked switch helps to clean up multi-boolean logic.

https://github.com/ardanlabs/gotraining/blob/master/topics/go/algorithms/searches/binarysearch/binarysearch.go#L11

**Comment by Miraddo** [comment]
Oh, I had a lot of mistakes, right I should make my comments better, and using switch more readable and cleaner than my previous code that I used if statement,
I will fix my codes with the tips that you told me.

**Pull request merged**
