### PR TITLE
fix: incorrect memory alignment comment for tbp struct

### PR DESCRIPTION
**Pull request by XmchxUp**

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
Cool! Can you add yourself to the CONTRIBUTORS file please.

**Comment by XmchxUp** [comment]
> Cool! Can you add yourself to the CONTRIBUTORS file please.

OK, I've added it.

**Comment by ardan-bkennedy** [comment]
Sorry. This list needs to be in alphabetical order. I do see there is another name out of order. :(

I can fix that mistake, but please put your name where it belongs in the list.

**Comment by XmchxUp** [comment]
Thanks for the guidance.

> Sorry. This list needs to be in alphabetical order. I do see there is another name out of order. :(
> 
> I can fix that mistake, but please put your name where it belongs in the list.

**Pull request merged**
