### PR TITLE
Update array exercise description

### PR DESCRIPTION
**Pull request by NikitaKolesov**
Fix inconsistency in array exercise description and provided answer

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
Maybe instead of saying first and second, we can say zero-value array.

// Declare an array of 5 strings with each element initialized to its zero value.
//
// Declare a second array of 5 strings and initialize this array with literal string
// values. Assign the array with values to the zero-value array and display the results after the assignment.
// Display the string value and address of each element.

**Comment by NikitaKolesov** [comment]
> Assign the array with values to the zero-value array and display the results after the assignment.

This way the answer should be updated as well because of "and display the results after the assignment"
(By adding print I suppose)
To maintain current answer version I suggest to skip that part:
"... Assign the array with values to the zero-value array. Display the string value and address of each element."

Do you agree?

**Comment by ardan-bkennedy** [comment]
Sounds Good. Anything to make it clearer.

**Comment by NikitaKolesov** [comment]
I read the description all over again several times and realized that my English let me down.
Description is fine in it's current state.

**Pull request closed without merging**
