### PR TITLE
Basics

### PR DESCRIPTION
**Pull request by ardan-bkennedy**
Code changes for consistency with the rest of the training.

### CODE REVIEW

**Comment by markbates** [comment]
I've never been a big fan of the `example#` directory structure, I've been finding it difficult to find the code example I need. I'm even less of a fan of the `example#.go` file naming, since the idiomatic go says the `main` file is usually called `main.go`.

**Comment by ardan-bkennedy** [comment]
The reason I do that is because in the editor all you see main.go. You can easily lose track of the example you are on. Over time you know the examples. Trying to name each file with something more meaningful is time consuming.

**Comment by ardan-bkennedy** [comment]
If you want to switch the convention then I need to do it everywhere. I have some special topics where it was easy to name the folders.

**Comment by markbates** [comment]
The other benefit to not using `example#` as a folder name is adding/removing new sections is a pain, you need to rename folders and files and such.

**Comment by ardan-bkennedy** [comment]
Yes, that has hurt me once. But at this point we need to keep things consistent. I think you will find though when using your editor not having a set of tabs all saying main.go is going to help you.

**Pull request closed without merging**
